keys:
  - &admin_sgillespie 84F97C2EDCE62BCE0AA215BC163ED0907B84F3E9
  - &server_sean-work age1xctjfgc9t580qkfxgf3mma06th9x2g90vgkp6w66rp9cru6m6aesrmx9rl
  - &server_sean-pi age1mr3ha2mlst72x5x4ggwkvl0hgwptau9627as9gpk2ham5km7hshqta83fm

creation_rules:
  - path_regex: secrets/.*$
    key_groups:
      - pgp:
          - *admin_sgillespie
        age:
          - *server_sean-work
          - *server_sean-pi
