keys:
  - &admin_sgillespie 84F97C2EDCE62BCE0AA215BC163ED0907B84F3E9
  - &server_sean-work age1xctjfgc9t580qkfxgf3mma06th9x2g90vgkp6w66rp9cru6m6aesrmx9rl
  - &server_sean-pi age1qy7qw2wk5gcqaprfl5pye9y25p7r7vwsfsxzkzd85ysp9p89yu7qg070k0
  - &server_sean-nixos age1p0ct7yt3yzm9dgpm8unq74ea7jtr74myzvn5dxl5r9p268m68vms40c0dn
  - &server_sean-pi-public age1tm6ewhady2xh87dyywj64m5kw9q27ung3dflawe3989nn3zrzs0sh2jpye

creation_rules:
  - path_regex: secrets/home-assistant.yaml$
    key_groups:
      - pgp:
          - *admin_sgillespie
        age:
          - *server_sean-pi
  - path_regex: secrets/.*$
    key_groups:
      - pgp:
          - *admin_sgillespie
        age:
          - *server_sean-work
          - *server_sean-pi
          - *server_sean-pi-public
          - *server_sean-nixos
