# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" ];
  boot.initrd.kernelModules = [ "vfat" "nls_cp437" "nls_iso8859-1" "usbhid" ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/23e405d1-ef42-424c-99ef-aeae804575d3";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/1ADD-11EA";
      fsType = "vfat";
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/e58e50e2-3143-4ebd-ac86-793997d61dbf";
      fsType = "ext4";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/18e6fb7e-21c7-4b58-b135-ce1e69e931c3"; }
    ];

  boot.initrd.luks = {
    yubikeySupport = true;
    
    devices."encrypted-home" = {
      device = "/dev/disk/by-uuid/f82912bd-63f5-4d1e-9bd5-9f31cd72ba7b";
      
      yubikey = {
        slot = 2;
        twoFactor = false;
        gracePeriod = 300;
        keyLength = 64;
        saltLength = 16;
        
        storage = {
          device = "/dev/disk/by-uuid/1ADD-11EA";
          fsType = "vfat";
          path = "/crypt-storage/default";
        };
      };
    };
  };
    
  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp34s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
