#!/bin/zsh

# History
HISTFILE=~/.histfile
HISTSIZE=9999
SAVEHIST=9999

# Key bindings
bindkey -e

# zsh completion
autoload -Uz compinit
compinit

# Prompt
source $HOME/.config/zsh/prompt.zsh
set_prompt

setopt interactivecomments

# aliases
if [[ ! -n "${EC+DEFINED}" ]]; then
    EC=emacsclient
fi

alias ec="$EC -n"
export EDITOR='nvr --nostart --remote-tab-wait +"set bufhidden=delete"'

# make sure color output is set
export CLICOLOR=

# set the clipboard for pass
export PASSWORD_STORE_X_SELECTION=primary

# SSH Agent, if we can find it
if [[ -S "${XDG_RUNTIME_DIR}/gnupg/S.gpg-agent.ssh" ]]; then
    export GPG_TTY="$(tty)"
    export SSH_AUTH_SOCK="/run/user/$UID/gnupg/S.gpg-agent.ssh"
elif [[ -S "${XDG_RUNTIME_DIR}/ssh-agent.socket" ]]; then
    export SSH_AUTH_SOCK="${XDG_RUNTIME_DIR}/ssh-agent.socket"
fi

# Editors
alias ec="$EC -n"

function ecbuffer {
    TMP="$(mktemp /tmp/emacsstdinXXX)"
    cat > $TMP
    ec --alternate-editor /usr/bin/false --eval "(let ((b (create-file-buffer \"*stdin*\"))) (switch-to-buffer b) (insert-file-contents \"${TMP}\"))"
    rm $TMP
}
