# Make C-a escape
unbind C-b
set -g prefix C-a
bind a send-prefix

set -g mode-keys vi

# Set TERM
set -g default-terminal "screen-256color"

# Colors
set -g status-bg "#16161D"
set -g status-fg "#DCD7BA"
set -g status-left ""
set -g status-right "#[fg=#DCD7BA]#H"

# Highlight active window
set-window-option -g window-status-current-fg "#C0A36E"
