;==========================================================
;
;
;   ██████╗  ██████╗ ██╗  ██╗   ██╗██████╗  █████╗ ██████╗
;   ██╔══██╗██╔═══██╗██║  ╚██╗ ██╔╝██╔══██╗██╔══██╗██╔══██╗
;   ██████╔╝██║   ██║██║   ╚████╔╝ ██████╔╝███████║██████╔╝
;   ██╔═══╝ ██║   ██║██║    ╚██╔╝  ██╔══██╗██╔══██║██╔══██╗
;   ██║     ╚██████╔╝███████╗██║   ██████╔╝██║  ██║██║  ██║
;   ╚═╝      ╚═════╝ ╚══════╝╚═╝   ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝
;
;
;   To learn more about how to configure Polybar
;   go to https://github.com/polybar/polybar
;
;   The README contains a lot of information
;
;==========================================================

[colors]
background     = #3d2a1f
background-alt = #50392a
foreground     = #c4b896                                                                                                                                                                                                            
primary        = #b58900
secondary      = #cb4b16
alert          = #d75f00
disabled       = #7a6258

[bar/main]
width = 100%
height = 28pt
radius = 6

; dpi = 96

background = ${colors.background}
foreground = ${colors.foreground}

line-size = 3pt

border-top-size = 2pt
border-left-size = 2pt
border-right-size = 2pt
border-bottom-size = 0pt
border-color = #00000000

padding-left = 0
padding-right = 1

module-margin = 1

separator = |
separator-foreground = ${colors.disabled}

font-0 = "Atkinson Hyperlegible Mono:size=11;3"
font-1 = "Font Awesome 7 Free Solid:size=12;3"

modules-left = xworkspaces xwindow
modules-right = filesystem memory cpu temperature battery wlan eth date utc pulseaudio systray

cursor-click = pointer
cursor-scroll = ns-resize

enable-ipc = true

; wm-restack = generic
; wm-restack = bspwm
; wm-restack = i3

; override-redirect = true

; This module is not active by default (to enable it, add it to one of the
; modules-* list above).
; Please note that only a single tray can exist at any time. If you launch
; multiple bars with this module, only a single one will show it, the others
; will produce a warning. Which bar gets the module is timing dependent and can
; be quite random.
; For more information, see the documentation page for this module:
; https://polybar.readthedocs.io/en/stable/user/modules/tray.html
[module/systray]
type = internal/tray

format-margin = 8pt
tray-spacing = 8pt

[module/xworkspaces]
type = internal/xworkspaces

label-active = %name%
label-active-background = ${colors.background-alt}
label-active-underline= ${colors.primary}
label-active-padding = 1

label-occupied = %name%
label-occupied-padding = 1

label-urgent = %name%
label-urgent-background = ${colors.alert}
label-urgent-padding = 1

label-empty = %name%
label-empty-foreground = ${colors.disabled}
label-empty-padding = 1

[module/xwindow]
type = internal/xwindow
label = %instance%: %title:0:30:...%

[module/filesystem]
type = internal/fs
interval = 25

mount-0 = /

format-mounted = <label-mounted>
format-mounted-prefix = " "
format-mounted-prefix-font = 2
format-mounted-prefix-foreground = ${colors.disabled}
label-mounted = %used%/%total%
label-mounted-foreground = ${colors.foreground}

warn-percentage = 85
format-warn = <label-warn>
format-warn-prefix = " "
format-warn-prefix-font = 2
format-warn-prefix-foreground = ${colors.alert}
label-warn = %used%/%total%
label-warn-foreground = ${colors.alert}

label-unmounted = %mountpoint% not mounted
label-unmounted-foreground = ${colors.disabled}

[module/pulseaudio]
type = internal/pulseaudio

format-volume-prefix = " "
format-volume-prefix-font = 2
format-volume-prefix-foreground = ${colors.disabled}
format-volume = <label-volume>

label-volume = %percentage%%
label-volume-foreground = ${colors.disabled}

format-muted-prefix = " "
format-muted-prefix-font = 2
format-muted-prefix-foreground = ${colors.primary}

label-muted = %percentage%%
label-muted-foreground = ${colors.disabled}

[module/xkeyboard]
type = internal/xkeyboard
blacklist-0 = num lock

label-layout = %layout%
label-layout-foreground = ${colors.disabled}

label-indicator-padding = 2
label-indicator-margin = 1
label-indicator-foreground = ${colors.background}
label-indicator-background = ${colors.secondary}

[module/memory]
type = internal/memory
interval = 2

format = <label>
format-prefix = " "
format-prefix-font = 2
format-prefix-foreground = ${colors.disabled}
label = %used%/%total%

warn-percentage = 85
format-warn = <label-warn>
format-warn-prefix = " "
format-warn-prefix-font = 2
format-warn-prefix-foreground = ${colors.alert}
label-warn = %used%/%total%
label-warn-foreground = ${colors.alert}

[module/cpu]
type = internal/cpu
interval = 2
format-prefix = " "
format-prefix-font = 2
format-prefix-foreground = ${colors.disabled}
label = %percentage%/%percentage-sum%+
label-foreground = ${colors.foreground}

warn-percentage = 50
format-warn = <label-warn>
format-warn-prefix = " "
format-warn-prefix-font = 2
format-warn-prefix-foreground = ${colors.alert}
label-warn = %percentage:2%%/%percentage-sum%+
label-warn-foreground = ${colors.alert}

[module/temperature]
type = internal/temperature
interval = 1
thermal-zone = 0

; Select thermal zone by name
; The name has to match the contents of /sys/class/thermal/thermal_zone*/type
; for the desired thermal zone.
; zone-type = x86_pkg_temp

; Full path of temperature sysfs path
; Use `sensors` to find preferred temperature source, then run
; $ for i in /sys/class/hwmon/hwmon*/temp*_input; do echo "$(<$(dirname $i)/name): $(cat ${i%_*}_label 2>/dev/null || echo $(basename ${i%_*})) $(readlink -f $i)"; done
; to find path to desired file
; hwmon-path = 

base-temperature = 0
warn-temperature = 75

format = <label>
label = %temperature-c%
label-foreground = ${colors.foreground}

format-warn = <label-warn>
format-warn-prefix = " "
format-warn-prefix-font = 2
format-warn-prefix-foreground = ${colors.primary}
label-warn = %temperature-c%
label-warn-foreground = ${colors.primary}

[module/battery]
type = internal/battery
battery = BAT0
adapter = AC
full-at = 90
low-at = 10

poll-interval = 5

ramp-capacity-0 = 
ramp-capacity-1 = 
ramp-capacity-2 = 
ramp-capacity-3 = 
ramp-capacity-4 = 
ramp-capacity-font = 2
ramp-capacity-foreground = ${colors.disabled}

format-charging    = <ramp-capacity> <label-charging>
format-discharging = <ramp-capacity> <label-discharging>
format-full        = <ramp-capacity> <label-full>
format-low         = <label-low>

label-charging    = %percentage%%+
label-charging-foreground = ${colors.disabled}
label-discharging = %percentage%%
label-discharging-foreground = ${colors.disabled}
label-full        = %percentage%%
label-full-foreground = ${colors.disabled}

label-low         = %{T2}%{T-} %percentage%%
label-low-foreground = ${colors.primary}

[network-base]
type = internal/network
interval = 5
format-connected = <label-connected>
label-connected-foreground = ${colors.disabled}

format-disconnected = <label-disconnected>
label-disconnected = 

[module/wlan]
inherit = network-base
interface-type = wireless
label-connected = %essid% %local_ip%

[module/eth]
inherit = network-base
interface-type = wired
label-connected = %ifname% %local_ip%

[module/date]
type = internal/date
interval = 1

date = %Y-%m-%d %H:%M:%S %{F#7a6258}%Z
date-alt = %Y-%m-%d %H:%M:%S

label = %date%
label-foreground = ${colors.primary}
format-foreground = ${colors.primary}

[module/utc]    
type = custom/script
interval = 1
exec = TZ=UTC date '+%H:%M:%S UTC'
format-foreground = ${colors.disabled} 

[settings]
screenchange-reload = true
pseudo-transparency = false

; vim:ft=dosini
