secret_key: ENC[AES256_GCM,data:8iN4FqFqTJK77A==,iv:su06yuZczJNmdKG2b1XRplNXeBI6iZsLaaPA6Exc2mI=,tag:J+90wHsg3a+3GzoDhyn6KQ==,type:str]
hashedPasswords:
    agillespie: ENC[AES256_GCM,data:dfPRRKyeGonBczoU1WjqaYeg135WjsLcuieMBobwi6TDg27PaKXW1YTDVDE0VO7wo+pENqFtn+XNXi3xpzRptGe4I8OxsDku1w==,iv:UtHP9wWvipwpqvuamtoKUygJSFGRpDPhYJALNp2DoX4=,tag:jAQuWm19FXpVXJhlfM/aSQ==,type:str]
    sgillespie: ENC[AES256_GCM,data:KzBy2yKLOZG551tDd4sU/qgVyN/Q7ANogWlTUz+DcNJEi5I76zcgKsLY9ncRIg1//syUsGjChQA5FFFifm5LswAjvNls37zhRQ==,iv:JpN/6YHITbQcgB6DJX1Hdliz8dZJ+KOJR5HmIQKXK9M=,tag:gfiYXizWuV6WJqHEJjkbsw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xctjfgc9t580qkfxgf3mma06th9x2g90vgkp6w66rp9cru6m6aesrmx9rl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCeDNIbnpyZXNrSkhZUEVi
            am00YVNlYU45S2ZJNnp5UmJlNHBLdm0vcTI4CjhRSkpJTnVQbzgzQUNXeWRnWmUr
            RU50Uk1IcjBadWxlc1diVERMbTViZjAKLS0tIHROWGNZeHgwcERHVThLNnN2MXRU
            VXlidHpDUUpTL2QwTnozM3FVZU5PU0UKtr10yPwKSqw1Ah5t8JUIGApsQYFO0msk
            iqAiOV8KoWzCNaa2F/fFJQPIPlY3DP7T2hfk3ar38F+k4zJrhIAAsg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1qy7qw2wk5gcqaprfl5pye9y25p7r7vwsfsxzkzd85ysp9p89yu7qg070k0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFSm5WSlk0NUhhZ2JONStZ
            ZXUxKzV2SlkwbnRnRmNKNzZJM0RhdkRjeUZjCmNCTkVhYVVJcEpjUHY3cWRFK0ZD
            dnJRUDkwZWdiL29EcmI1M1pLMy9pTHMKLS0tIFoxWElGSG8yOEc5aUI3U1lFeTNv
            VDhtUDdaVUtWSWh1RlJkdGU0Ykl2WEUK8E+dQUrpWgcYXEg0GirwSVJekbzAydNC
            pw+tgAc9w5WwdyTpz8i+NkveEBfBzGtFe7GixOksChioymBNsa1jiA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1p0ct7yt3yzm9dgpm8unq74ea7jtr74myzvn5dxl5r9p268m68vms40c0dn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBMkUvWDMvVHk4N2o1aFVa
            MHRSK2VEdGlkcWU0eU1wWGpEQ2dEWE42UzN3CkxVb3Vkei9TSUFEeWl1KzdvaXFH
            QzNCSjBhMTlJQzRvNlhOYWZ3RDhmSmsKLS0tIE01K0YvWGRRb2FHQi90Wk40OW5W
            Vm83eUNONWdyb0JCaThmZm9SVG91SkkKd4VFV2s/3SiWVf/RufhDogSR6sjvPb3k
            YjFW9ewnedsxGlB7MC+z/0YFwScGlJy54A9OzRUu9wGOGgpYe+/t1w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-04T03:07:11Z"
    mac: ENC[AES256_GCM,data:pp8tWw8bsk69mg27y4Gwx0sZ1yahW6pgmXN7mwoh+JGWI7vSCx8msdNdaWhzMhelRqUOBSfWFgMGIjHqve1FBlX72NSB5JiToYLu1kBfO/fC3ob0bpy1loi8zzJ6ElQn+Qk1YLQ5rMGwC4TxhHzS2DiJeChDkY2qZ5k2HBD+Oa8=,iv:GAakAPEQWx9Cw7zdzK5YWuca4zXtWPu/x+79XA19bSU=,tag:ONrFjPH2POi7OK3CdCh/MA==,type:str]
    pgp:
        - created_at: "2025-03-10T14:55:18Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA6Co6lV8jE6xAQ//TAhw5ULqtzAT3MF75vKn98e5hcDw+B/jRIGRZQ+H7fmz
            nH5Fsp+77DgzDeMliE5X9N2Rxj/QS0qNuW7Drk9K5oPxti/ua41FuD8Y9Mq4O+go
            YnSIFhE4SLUohN2K44TKMvlu4jm2cH+ftoiaYLCgt+E9+UpccptZA2kiGiU+QtnJ
            BjII/URWD/0iUiReZWFq64FN5nLlKGYunSIkwlOpSx69NWBvFpg49mu2OqWbiMAw
            V7GXmS0UOBSY2tLYtw9RUaJHc9a+PblgOcmpm/8I96/G4781dYy99Zl+P8zgC4Z6
            rUuuodmO7sm17ymRJtYT+Mzl0doh5w/zI8HSfdnrbMYDA7ZLUB4uaxs1av8KBygi
            NVZfS7RJEZhCZHcaD2PGNxw0pwW+H/v3XMVzvh2Zrj5naVKI2TbCCN3Bou5R/ZJk
            7btQNnt6sWqVfMH/LcpJvZ/W62Z6Ly8peSPkhMLMsjMY8m7W93R1GK5JMiCaEQrb
            OO5zx+M+FUkQQjPuzERuE9WfLjMlRVGr+5eLQAhlO156M7TUTk7VXCjZYtyYhNWI
            3hz6J73azp9IXlmHAQI+1wjH9D0xIbNpbpLMFBY4OOahVlY1R+z/AYWd42y3qznx
            cREYs3k1/QgCtMJmWVqBX6jkWMt6BKP+bMl54mXW8s1f7EZFNYdHtuP+XtgnNITS
            XAGX7s7si2xD38HuibtBQL3Y0Rq+rO8YvsQ3PFrVcd0KfXEUz6ptDaQ1OwgeKeM7
            cwH3nW4FNKlCJU7OnwZeWBk3ZFWAwQbvsVE2e/Ib51tV6rjN7sASdgywQQR8
            =rrBO
            -----END PGP MESSAGE-----
          fp: 84F97C2EDCE62BCE0AA215BC163ED0907B84F3E9
    unencrypted_suffix: _unencrypted
    version: 3.8.1
