secret_key: ENC[AES256_GCM,data:8iN4FqFqTJK77A==,iv:su06yuZczJNmdKG2b1XRplNXeBI6iZsLaaPA6Exc2mI=,tag:J+90wHsg3a+3GzoDhyn6KQ==,type:str]
hashedPasswords:
    agillespie: ENC[AES256_GCM,data:dfPRRKyeGonBczoU1WjqaYeg135WjsLcuieMBobwi6TDg27PaKXW1YTDVDE0VO7wo+pENqFtn+XNXi3xpzRptGe4I8OxsDku1w==,iv:UtHP9wWvipwpqvuamtoKUygJSFGRpDPhYJALNp2DoX4=,tag:jAQuWm19FXpVXJhlfM/aSQ==,type:str]
    sgillespie: ENC[AES256_GCM,data:KzBy2yKLOZG551tDd4sU/qgVyN/Q7ANogWlTUz+DcNJEi5I76zcgKsLY9ncRIg1//syUsGjChQA5FFFifm5LswAjvNls37zhRQ==,iv:JpN/6YHITbQcgB6DJX1Hdliz8dZJ+KOJR5HmIQKXK9M=,tag:gfiYXizWuV6WJqHEJjkbsw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xctjfgc9t580qkfxgf3mma06th9x2g90vgkp6w66rp9cru6m6aesrmx9rl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSbzUrMFBtWWxtS3BQMHdk
            bURVMEU4YVdITWtYVUR3ZFMrb1IxbWUyMEJzCkdxS2cwK2hBa0gwNVFubUlhMXA0
            Y0NaZFRYVmZNaDlKS1dvRFIwbEI5b3MKLS0tIGhVY3cxME9oYmYrdHFEcnJEcEFx
            eWsxVkFWMTFNZ3l4UnhJVHAzVHlHQmcKsrGaLdHxRvjam6/3Q7zZ1/WS9mU3UjgP
            zBI+JxKm+y8s2oP+xdheDeJUSK+TGVp7RQR+vu8MeOvmW4XDha09Xw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1mr3ha2mlst72x5x4ggwkvl0hgwptau9627as9gpk2ham5km7hshqta83fm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWUlZIMUVoY2h5RHlFRStr
            Yjd0WVd1cDkxWktGMFpuTjIxWnVqc0svRGd3Ck5pdWhINDUxMkhFQ1hUYWhvNzFm
            Q0RKeEI2S2c5by9WaHNhWWtyZlNYZmMKLS0tIHVvd0hxSTNMUU05bUJMYjJUaDJR
            K2RXQ2hGellEakVkTENKUVhOYlVTOEkKzqEiDRzjjnHRKWyjPrUoGrT62qjoh3z1
            m5jLo1QKeFGSQDRHN1L45OsgTVQyxSRrUjKZNwVqBc8TQiCN1mPg9g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-04T03:07:11Z"
    mac: ENC[AES256_GCM,data:pp8tWw8bsk69mg27y4Gwx0sZ1yahW6pgmXN7mwoh+JGWI7vSCx8msdNdaWhzMhelRqUOBSfWFgMGIjHqve1FBlX72NSB5JiToYLu1kBfO/fC3ob0bpy1loi8zzJ6ElQn+Qk1YLQ5rMGwC4TxhHzS2DiJeChDkY2qZ5k2HBD+Oa8=,iv:GAakAPEQWx9Cw7zdzK5YWuca4zXtWPu/x+79XA19bSU=,tag:ONrFjPH2POi7OK3CdCh/MA==,type:str]
    pgp:
        - created_at: "2024-07-03T20:37:10Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA6Co6lV8jE6xAQ//f1IaqbT+6EiFM+cO6f5tc9mSwFsG6rsuDcQqwoVFo4J6
            O3sIz58v/VPd117wrAMcloDkL81tOaedQ8/2VG9BD2uCunP1MOOb4pGLxcpD+gqT
            L46Y6t0fBv6bHY4Yuh2SH/Mg3NkFMY46XWfZvzFFkyKr0g5OFRhZqCBZe/uhYL2V
            8eJSoaqUimJz9jsUvRg1stWsYrbjkRbLn4r0RJbDxhkYjbbIu2/BjbC5OxuM9aNz
            jd71GHvXj8nwD9La3RyWJRukfMxzHCAho/ffBiVsLpAHFe3Fas7epy34pMbGi6mn
            8p3l/+X3QKijx2FudOHwcllMb6WGWhencQ687EShEJXQ2MR/lMgRCIyOBd9x7GaO
            KSb2hjLmeC/NlVAmxXsz9kVJsR89QCzxQNkuYJZWaaI2RbMQw5eT5XsYtOkT0Vcy
            W4UKu9Yo5EmRVRIbPuOI4ZBwLkRVguHEV44ZsA9QECvfkUPFtI52FT70NITdmiNN
            Rf+kqwLi27AFg/6Wd4h0X+DRt7UlphjnkShw9f11Muu75OxeGI8Sqz0tbTq++GoU
            +gQHSpfHNFA7HjMsKkQWa6MBsbvc5YlD7WwAExD1TfaDJqNV/5mhZLefvDIp9DWl
            yKPKU2Ad4A9RSQHniCPhfUubCXnCtqiihuxqCIRa/wrpDWoqmQAbkfDkf751I0vS
            XAH71b8awYfI7kPaqs0ceUEKJdWp3rq8lwPY0/NeG7K0v2MNJvi/Sf9GJLG2JP9P
            8n4tmqvTAUM68KLBenrXJiP1+eoxU4e4h81wNem/+i4iDRNEW1jgYsxQwX6k
            =+VXv
            -----END PGP MESSAGE-----
          fp: 84F97C2EDCE62BCE0AA215BC163ED0907B84F3E9
    unencrypted_suffix: _unencrypted
    version: 3.8.1
