secret_key: ENC[AES256_GCM,data:8iN4FqFqTJK77A==,iv:su06yuZczJNmdKG2b1XRplNXeBI6iZsLaaPA6Exc2mI=,tag:J+90wHsg3a+3GzoDhyn6KQ==,type:str]
hashedPasswords:
    agillespie: ENC[AES256_GCM,data:dfPRRKyeGonBczoU1WjqaYeg135WjsLcuieMBobwi6TDg27PaKXW1YTDVDE0VO7wo+pENqFtn+XNXi3xpzRptGe4I8OxsDku1w==,iv:UtHP9wWvipwpqvuamtoKUygJSFGRpDPhYJALNp2DoX4=,tag:jAQuWm19FXpVXJhlfM/aSQ==,type:str]
    sgillespie: ENC[AES256_GCM,data:KzBy2yKLOZG551tDd4sU/qgVyN/Q7ANogWlTUz+DcNJEi5I76zcgKsLY9ncRIg1//syUsGjChQA5FFFifm5LswAjvNls37zhRQ==,iv:JpN/6YHITbQcgB6DJX1Hdliz8dZJ+KOJR5HmIQKXK9M=,tag:gfiYXizWuV6WJqHEJjkbsw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xctjfgc9t580qkfxgf3mma06th9x2g90vgkp6w66rp9cru6m6aesrmx9rl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrTm40OHZaeGlORVUrQS9n
            WnRGSmxQUVFwYmJkOGoyTTdGK09pN1ltbXhBCnM2OW1PY09SRm1GdVBlOHNjUzcx
            MjhpSGUwZEZ2bStpTVkwYzlnUVdIYVkKLS0tIDJUVWptS3pvUkpKNDJSZWFGYWV4
            TExvRE5JQW8vWWhQdDBSZDJEa1NSVEkK4h4lkQ98dv4RsJoVnEVKNuJqGMJxAqpW
            RJDVCAwfS0+yrwF02TpyDBoSo46cW/HSC0Im7EStYcQu9A1cLJ3fhw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1mr3ha2mlst72x5x4ggwkvl0hgwptau9627as9gpk2ham5km7hshqta83fm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrTDhMQ05uYWRFUjBKMDlz
            cGs5OFNOOUhrbjhSQVFWNEhrVjFoZ2ZTOURjCmZBd3RFa0p1NDM3cDdIQTZYM3ZS
            bXBXZGk2V3JvdngrRkNxNUYySzNockkKLS0tIDl1cUNtbWl1V0w2L3lYdFQrWDd0
            V2hEL011enVFeG8rN3ZYS0lwVWZJRTAK9PrX1+ft2ubcxRJ0W6EXuQhNN+jRHHed
            7TVzSMVIoK60B/yjMIWYPyLJiYWri7VIyyqZ0525qxeefVm0AiTbSw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1p0ct7yt3yzm9dgpm8unq74ea7jtr74myzvn5dxl5r9p268m68vms40c0dn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3TmpjMGxTbU52NnhWUWRB
            eER0V3c3N1cxcGdEd2Nxb3BzdXZtK2RXNVdvCi9qaG1UQzNHdEdGK1ZIdFcxTjRQ
            U21FZDdHWVRkdmxrcVlmTXhEMCt1eUEKLS0tIFcwNnF5V1JCSi9rdGVpZ2gwOUdp
            Q2dUQjhqZmFHSjZUSGQ2NFl0QlJHdXcK6AuhdqGIiu6PJR77gaKTMSMY84iLmaSR
            RNeNpi95HEvFcU+h/8DZLLQhmwaJZ16XRDqJLL3URI05iIZsqjqlyg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-04T03:07:11Z"
    mac: ENC[AES256_GCM,data:pp8tWw8bsk69mg27y4Gwx0sZ1yahW6pgmXN7mwoh+JGWI7vSCx8msdNdaWhzMhelRqUOBSfWFgMGIjHqve1FBlX72NSB5JiToYLu1kBfO/fC3ob0bpy1loi8zzJ6ElQn+Qk1YLQ5rMGwC4TxhHzS2DiJeChDkY2qZ5k2HBD+Oa8=,iv:GAakAPEQWx9Cw7zdzK5YWuca4zXtWPu/x+79XA19bSU=,tag:ONrFjPH2POi7OK3CdCh/MA==,type:str]
    pgp:
        - created_at: "2024-07-13T19:46:06Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAwAAAAAAAAAAAQ//SEzEGZegya+j1G4QDJxqe39czTDRFGyNxPDg6RVc5Scz
            1vG2DVT27ouGx4JR3uuq7kfzL5MLtgL7dJTuR9h8TRSAONPJt8dwAd/SadhH0tmW
            vfi1/kcwix2pakcN//SvOD0GDOyqxihNJGRHKWglamSJYW7YqLy1Yt0OqyCikgS2
            t9nUPwePlqh7T0oWV82PozzbM1TxAKMmXT4NWA7R75/f4TM7AXNgHVOoGPaPZEC6
            YwHnUUpWu1TUBe//ckByUvgRcrJ2wBKriwLRcrXwNWabwydBOHxmwYNBXmkFAlmd
            tuFJGgjrrXXoGt4dER12mwNA9DykXIyEhi3Ju0aAt4sxz+nsMhNQkI9P24Wmejfk
            rY0dxE1OtZA3Ip1/Oyp2zv/JnBdgZPlnVhxvv9qgpCvssJy4Xp+ncQouOJTOYVgb
            dB+PJq91mZuO3MZCZ/BT0Blzdqrl+tINCb2WrX3mqDCdzrzDDBBzrGxvy7kZWJKR
            URNhU4VNLuhDwdS4gjNUUYLnaQKQOyxuNABR3ViSNBeU8ds0+4W1M06E/I+LNDFH
            Uhgii/XeKvZkt6Oewk7mNcvKsfmoWt7oftZsyvNdO22rTCTJ4hguOZo1sQfJbEsB
            986ZykAM492JPPN3FewDwVUl6l5r7ZoNzARC6xg+JxUa+6yNO0u3NNAQDd5Y4V/S
            XAFij/6DkUPnOFLKX18BnElLm16VY13nKzGX7Lp1Xs8ZcePRdEAzo6hiVmXlQLGI
            AxLZU9IZCUPp0PtbWOLoX6hz2Ises/6LW4lyn5D9BlniVKemsZK2+Ay4aE7r
            =rx3X
            -----END PGP MESSAGE-----
          fp: 84F97C2EDCE62BCE0AA215BC163ED0907B84F3E9
    unencrypted_suffix: _unencrypted
    version: 3.8.1
