secret_key: ENC[AES256_GCM,data:8iN4FqFqTJK77A==,iv:su06yuZczJNmdKG2b1XRplNXeBI6iZsLaaPA6Exc2mI=,tag:J+90wHsg3a+3GzoDhyn6KQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xctjfgc9t580qkfxgf3mma06th9x2g90vgkp6w66rp9cru6m6aesrmx9rl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0ZkJHMTdUUFN5OU5sajUw
            MlNNdnY3ZHo1K1hYZFByb0hXNjRTcGI2TEhNCmxicUFFb2NGbmdqS3BtR2VvYzBW
            NURJRnhLODhiN2JDKzFXNGNDYll6dW8KLS0tIFRLWnU4dlhpREN6SHp1c3RPQ3JO
            b3AwaDlWczhTSFlDZVRwSEEvWVp3RmMK7S0Vf9NfutKRZfKZZrCsmQrC2utC3Lfu
            UJxV33ba7gC/tyKYNlbjBMAyTwDLR/GThaDhS2/fJ3ODgSb/7Sh2PA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-03T16:59:15Z"
    mac: ENC[AES256_GCM,data:jag6Miq6iFmWqeQ7//Gb9+Op8xlToSx1HPP1hnGNLHB7n/ACQsgoQeXPeDU96m1YFCDVaRRiNQ5zv6RiTLpVflueGkLCkpQb1CM+640CNFUxAkOk5oVMJ0cgXj2TrOeKAZ2qB0HmnFqezLSPfO2/awj2v2B2GOieZS0zT0K7QG8=,iv:jnfh1ymo6ZU5OuTOkMKprMLgMo3tQIiaoYFAH+9d5EM=,tag:FVl29FX0mGvl1ucemG6eZQ==,type:str]
    pgp:
        - created_at: "2024-07-03T17:07:19Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA6Co6lV8jE6xARAAi0ntG1ayzNnc0RZKMuPLUc39SDYA6lKOZc/BbfSPpEa6
            jfF/4gnQR+mqDCT/TxZUI7ChPKIBSHlfGwOuogqL7Dp6h86T2652fXmlOrg+zZ20
            DMyqbO6pEFcVPFVv2anLOpY+WLT1tMHQg73PfzkX1hZUnLE5kYwa+VOqxzLLLBvf
            +rZoMvEeDZqO/LDWrUgM273/gameHluEet9F4ZT1tqpnZgjOQzk3ioMTLyL7COsm
            k0SoD3wwmmhdaDOhXKouLSjHfixTn19gUAn+36rrYGBaNxiQQZivkbwtSRPe3AHh
            a2mDAfmDtUBPXizIOpxRvvN9GVl0gyWF5beswRxGlpbP2bBh2n0xJA8pta5NFlO+
            WPIJZVFXl51YYq1vPZV2wh6k7yre8VV8fnpj0G7EoCXDFbq9C2kKxGNvMorsa3x1
            M2F08FMT3P6r8iTtUgDy7z7veaFFiCg3jJVTgXR9U+cjuxqTcxeeHto5nv154eiM
            f5JXp+O3yV2/yFE1Wf+enlPi+69UBIFvImRotaCPIwaqKf5P9JKr33UvBdK+KK7O
            wolPcpxD1+eeEOuPYOzLvz1U+HNNHwXONIahZ5SfgoEzSftx8F2nIlEanaW0C+Uc
            GYv43yFIosefyTLBU9qJWpgbRE0anVJCe3PrPV7xgSH1OOqSnHLRoxq7NoEfC7PS
            XAFVDG224YZOXrjWQdHSUmWHHtq6ruP6JXOEJYKjus//wwV4EN29myPwW6srXFFU
            pxUGjf+3aTQ1q0RZSUqkMXhCZNKwD54kAa95JfhKYXZF8DO4xHaF9hifrgNA
            =F3PR
            -----END PGP MESSAGE-----
          fp: 84F97C2EDCE62BCE0AA215BC163ED0907B84F3E9
    unencrypted_suffix: _unencrypted
    version: 3.8.1
